### ISSUE TITLE
Issue in local installation

### ISSUE THREAD

**Issue by Rajeshvegi** [factly/janaganana#10]
Hi all, 

Local installation is causing below issue, can some one please help..

Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Rajesh\AppData\Local\Temp\pip-build-lu1fl57w\python-memcached\setup.py", line 8, in <module>
        version=get_module_constant('memcache', '__version__'),
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\depends.py", line 164, in get_module_constant
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\depends.py", line 195, in extract_constant
    IndexError: tuple index out of range

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Rajesh\AppData\Local\Temp\pip-build-lu1fl57w\python-memcached\

**Comment by mthipparthi** [comment]
Hi @Rajeshvegi  , Please try to set up in Liniux environment with Python 2.7. Let me know incase of any issues.We are planning to create Docker Image fro easy installation that may take a while. Incase you are looking for only dtaa, i can help you with other options.
Regards
Mahesh

**Comment by mthipparthi** [comment]
@Rajeshvegi . Now it is on docker. Installation is just one command `docker-compose up`. Please have a look at that. Process is simplified.
